# CORE {{{
# Window number starting from 1
set -g base-index 1

# Use VIM mode
set-option -g mode-keys vi

# Enable mouse support
set-option -g mouse on

# [linux/alacritty] True color support
set  -g default-terminal "tmux-256color"
set -ag terminal-overrides "*256color:RGB"

set -g history-limit 100000

# Highlight the windows with activities in the status line
set -g monitor-activity on

# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0

# Refresh 'status-left' and 'status-right' more often
# set -g status-interval 1

# Emacs key bindings in tmux command prompt (prefix + :) are better than
# vi keys, even for vim users
set -g status-keys emacs

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on
# }}}
# BINDINGS {{{
# Global prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Bind key for reloading configuration
bind R source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display-message "Config reloaded"

bind \\ split-window -h
bind - split-window -v

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# indicator stays until a key is pressed
bind-key -r q display-panes -d 0
# swap pane visually
bind-key -T prefix C-q display-panes -d 0 'swap-pane -d -t "%%"'

# swap window
bind-key -T prefix C-w command-prompt -p "Swap window with:" 'swap-window -d -t "%%"'

bind-key -T prefix C display-popup -E "cat ~/.tmux-cheatsheet.md | less -R"
bind-key -T prefix C-h display-popup -E "cat $XDG_CONFIG_HOME/tmux/cheatsheet.txt | less -R"

# VIM style copy mode. OSC 52 -> system clipboard (terminal-dependent)
bind-key -Tcopy-mode-vi 'v' send -X begin-selection
bind-key -Tcopy-mode-vi 'y' send -X copy-selection-and-cancel
# }}}
# THEME {{{
set -g mode-style fg="#4C566A",bg="#EBCB8B"
set -g message-command-style fg="#4C566A",bg="#EBCB8B"
set -g message-style fg="#4C566A",bg="#EBCB8B"

set -g pane-border-style fg="#EBCB8B"
set -g pane-active-border-style fg="#D08770"

set -g status-position top

set -g status-style fg="#D8DEE9",bg="#4C566A"

# Set the inactive window color and style
set -g window-status-style fg="#81A1C1",bg=default
# set -g window-status-format ' #I #W '

# Set the active window color and style
set -g window-status-current-style fg=default,bg=default,bold
# set -g window-status-current-format ' #I #W '

set -g window-status-activity-style fg="#81A1C1",bg=default

set -g status-left "#[bold,bg=#5E81AC] #S #[bg=default] "
set -g status-right "#[bg=#5E81AC] %Y-%m-%d %H:%M:%S #[bold]#H "
# }}}
# PLUGINS {{{
# [TPM - Tmux Plugin Manager](https://github.com/tmux-plugins/tpm)
# <Prefix-I> Install plugins
# <Prefix-U> Update plugins
# <Prefix-Alt-u> Uninstall plugins (comment out plugin from the list first)

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'laktak/extrakto'

set -g @plugin 'tmux-plugins/tmux-cowboy'

# Move your tmux panes to better neighborhoods
set -g @plugin 'kristopolous/tmux-gentrify'

# tmux-lazy-restore {{{
# A tmux session manager plugin
set -g @plugin 'bcampolo/tmux-lazy-restore'

set -g @tmux-lazy-restore-save-all-key 'C-u'
set -g @tmux-lazy-restore-kill-launch-session 'on'
# }}}

# lloydbond/tmux-floating-terminal {{{
set -g @plugin 'lloydbond/tmux-floating-terminal'

set -g @floating_scratch_term 'Enter'
set -g @floating_scratch_to_active_win 'M-h'
set -g @floating_scratch_to_win 'M-l'
set -g @floating_active_pane_to_scratch 'M-m'
# }}}

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '$XDG_CONFIG_HOME/tmux/plugins/tpm/tpm'
# }}}
# vim: fdm=marker
